2024-10-07 12:10:16,571 INFO    MainThread:267253 [wandb_setup.py:_flush():68] Configure stats pid to 267253
2024-10-07 12:10:16,572 INFO    MainThread:267253 [wandb_setup.py:_flush():68] Loading settings from /home/one/.config/wandb/settings
2024-10-07 12:10:16,572 INFO    MainThread:267253 [wandb_setup.py:_flush():68] Loading settings from /home/one/julia/MWESN/wandb/settings
2024-10-07 12:10:16,572 INFO    MainThread:267253 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2024-10-07 12:10:16,572 INFO    MainThread:267253 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-10-07 12:10:16,572 INFO    MainThread:267253 [wandb_setup.py:_flush():68] Applying login settings: {'api_key': '***REDACTED***'}
2024-10-07 12:10:16,572 INFO    MainThread:267253 [wandb_init.py:_log_setup():476] Logging user logs to /home/one/julia/MWESN/wandb/run-20241007_121016-29b8cnxk/logs/debug.log
2024-10-07 12:10:16,572 INFO    MainThread:267253 [wandb_init.py:_log_setup():477] Logging internal logs to /home/one/julia/MWESN/wandb/run-20241007_121016-29b8cnxk/logs/debug-internal.log
2024-10-07 12:10:16,572 INFO    MainThread:267253 [wandb_init.py:init():516] calling init triggers
2024-10-07 12:10:16,572 INFO    MainThread:267253 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2024-10-07 12:10:16,572 INFO    MainThread:267253 [wandb_init.py:init():569] starting backend
2024-10-07 12:10:16,572 INFO    MainThread:267253 [wandb_init.py:init():573] setting up manager
2024-10-07 12:10:16,574 INFO    MainThread:267253 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-10-07 12:10:16,575 INFO    MainThread:267253 [wandb_init.py:init():580] backend started and connected
2024-10-07 12:10:16,576 INFO    MainThread:267253 [wandb_init.py:init():658] updated telemetry
2024-10-07 12:10:16,584 INFO    MainThread:267253 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2024-10-07 12:10:19,620 WARNING MsgRouterThr:267253 [router.py:message_loop():77] message_loop has been closed
2024-10-07 12:10:26,597 ERROR   MainThread:267253 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "/home/one/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/home/one/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 697, in init
    result = handle.wait(
  File "/home/one/.local/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 259, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
